services:
  db:
    image: postgis/postgis:17-3.5
    platform: linux/amd64
    container_name: veloceti_db
    restart: always
    environment:
      POSTGRES_DB: veloceti
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: change_me
    ports:
      - '5432:5432'
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data:
